<?php

use Illuminate\Database\Seeder;

class BarrioSeeder extends Seeder
{
    
    // php artisan db:seed --class=UsuarioSeeder

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('barrio')->insert([
            ['co_barrio' =>	1	, 'nb_barrio' => 'Barrio Alto Aguacatal',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	2	, 'nb_barrio' => 'Barrio Bajo Aguacatal',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	3	, 'nb_barrio' => 'Barrio la Legua',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	4	, 'nb_barrio' => 'Barrio Palmas I',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	5	, 'nb_barrio' => 'Barrio Palmas II',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	6	, 'nb_barrio' => 'Barrio Terrón Colorado I',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	7	, 'nb_barrio' => 'Barrio Terrón Colorado II',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	8	, 'nb_barrio' => 'Barrio Villa del Mar',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	9	, 'nb_barrio' => 'El Barrio Bajo Palermo',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	10	, 'nb_barrio' => 'El barrio Vista hermosa',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	11	, 'nb_barrio' => 'Urbanización Aguacatal',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 1, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	12	, 'nb_barrio' => 'Altos de Menga',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	13	, 'nb_barrio' => 'Arboledas',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	14	, 'nb_barrio' => 'Área Libre-Parque del Amor',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	15	, 'nb_barrio' => 'Arroyohondo',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	16	, 'nb_barrio' => 'Brisas de los Álamos',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	17	, 'nb_barrio' => 'Centenario',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	18	, 'nb_barrio' => 'Chipichape',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	19	, 'nb_barrio' => 'Ciudad los Álamos',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	20	, 'nb_barrio' => 'Dapa',                         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	21	, 'nb_barrio' => 'El Bosque',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	22	, 'nb_barrio' => 'Granada',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	23	, 'nb_barrio' => 'Juanambú',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	24	, 'nb_barrio' => 'La Campiña',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	25	, 'nb_barrio' => 'La Flora',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	26	, 'nb_barrio' => 'La Paz',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	27	, 'nb_barrio' => 'Menga',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	28	, 'nb_barrio' => 'Normandía',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	29	, 'nb_barrio' => 'Pacará',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	30	, 'nb_barrio' => 'Prados del Norte',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	31	, 'nb_barrio' => 'San Vicente',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	32	, 'nb_barrio' => 'Santa Mónica',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	33	, 'nb_barrio' => 'Santa Rita',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	34	, 'nb_barrio' => 'Santa Teresita',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	35	, 'nb_barrio' => 'Sect Altos Normandía-Bataclán','tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	36	, 'nb_barrio' => 'Urbanización La Flora',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	37	, 'nb_barrio' => 'Urbanización La Merced',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	38	, 'nb_barrio' => 'Versalles',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	39	, 'nb_barrio' => 'Vipasa',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 2, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	40	, 'nb_barrio' => 'Acueducto San Antonio.',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	41	, 'nb_barrio' => 'El Calvario.',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	42	, 'nb_barrio' => 'El Hoyo.',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	43	, 'nb_barrio' => 'El Nacional.',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	44	, 'nb_barrio' => 'El Peñón.',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	45	, 'nb_barrio' => 'El Piloto.',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	46	, 'nb_barrio' => 'La Merced.',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	47	, 'nb_barrio' => 'Los Libertadores.',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	48	, 'nb_barrio' => 'Navarro-La Chanca.',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	49	, 'nb_barrio' => 'San Antonio.',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	50	, 'nb_barrio' => 'San Cayetano.',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	51	, 'nb_barrio' => 'San Juan Bosco.',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	52	, 'nb_barrio' => 'San Nicolás.',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	53	, 'nb_barrio' => 'San Pascual.',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	54	, 'nb_barrio' => 'San Pedro.',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	55	, 'nb_barrio' => 'Santa Rosa.',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 3, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	56	, 'nb_barrio' => 'Bolivariano',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	57	, 'nb_barrio' => 'Bueno Madrid',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	58	, 'nb_barrio' => 'Calima',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	59	, 'nb_barrio' => 'Evaristo García',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	60	, 'nb_barrio' => 'Fátima',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	61	, 'nb_barrio' => 'Flora Industrial',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	62	, 'nb_barrio' => 'Guillermo Valencia',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	63	, 'nb_barrio' => 'Ignacio Rengifo',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	64	, 'nb_barrio' => 'Industria de Licores',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	65	, 'nb_barrio' => 'Jorge Isaacs',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	66	, 'nb_barrio' => 'La Alianza',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	67	, 'nb_barrio' => 'La Esmeralda',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	68	, 'nb_barrio' => 'La Isla',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	69	, 'nb_barrio' => 'Las Delicias',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	70	, 'nb_barrio' => 'Manzanares',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	71	, 'nb_barrio' => 'Marco Fidel Suárez',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	72	, 'nb_barrio' => 'Olaya Herrera',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	73	, 'nb_barrio' => 'Popular',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	74	, 'nb_barrio' => 'Porvenir',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	75	, 'nb_barrio' => 'Salomia',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	76	, 'nb_barrio' => 'Santander',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	77	, 'nb_barrio' => 'Sultana-Berlín-San Francisco', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 4, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	78	, 'nb_barrio' => 'Bajo Salomia',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	79	, 'nb_barrio' => 'Barrio Residencial el Bosque', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	80	, 'nb_barrio' => 'Brisas de los Andes',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	81	, 'nb_barrio' => 'Brisas del Guabito',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	82	, 'nb_barrio' => 'Chiminangos 1.ª Etapa',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	83	, 'nb_barrio' => 'Chiminangos 2.ª Etapa',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	84	, 'nb_barrio' => 'El Sena',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	85	, 'nb_barrio' => 'La Rivera II',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	86	, 'nb_barrio' => 'Los Andes',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	87	, 'nb_barrio' => 'Los Guayacanes',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	88	, 'nb_barrio' => 'Metropolitano del Norte',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	89	, 'nb_barrio' => 'Palmeras del norte',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	90	, 'nb_barrio' => 'Paseo de los Almendros',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	91	, 'nb_barrio' => 'Plazas Verdes',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	92	, 'nb_barrio' => 'Santa Bárbara',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	93	, 'nb_barrio' => 'Torres de Comfandi',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	94	, 'nb_barrio' => 'Urbanización Barranquilla',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	95	, 'nb_barrio' => 'Villa del Prado',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	96	, 'nb_barrio' => 'Villa del Sol',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	97	, 'nb_barrio' => 'Villas de Veracruz',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 5, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	98	, 'nb_barrio' => 'Álamos',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	99	, 'nb_barrio' => 'Calimio',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	100	, 'nb_barrio' => 'FloraliaI',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	101	, 'nb_barrio' => 'FloraliaI Sector II',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	102	, 'nb_barrio' => 'FloraliaIA',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	103	, 'nb_barrio' => 'FloraliaII',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	104	, 'nb_barrio' => 'FloraliaIII',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	105	, 'nb_barrio' => 'Fonaviemcali',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	106	, 'nb_barrio' => 'Jorge Eliécer Gaitán',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	107	, 'nb_barrio' => 'La Rivera I',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	108	, 'nb_barrio' => 'Los Alcázares I',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	109	, 'nb_barrio' => 'Los Alcázares II',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	110	, 'nb_barrio' => 'Los Guadales',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	111	, 'nb_barrio' => 'oasis de comfandi',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	112	, 'nb_barrio' => 'Paso del Comercio',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	113	, 'nb_barrio' => 'PetecuyI etapa',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	114	, 'nb_barrio' => 'PetecuyII etapa',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	115	, 'nb_barrio' => 'PetecuyIII etapa',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	116	, 'nb_barrio' => 'popular',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	117	, 'nb_barrio' => 'San Luís I',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	118	, 'nb_barrio' => 'San Luís II',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 6, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	119	, 'nb_barrio' => 'Alfonzo López 1.ª Etapa.',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	120	, 'nb_barrio' => 'Alfonzo López 2.ª Etapa.',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	121	, 'nb_barrio' => 'Alfonzo López 3.ª Etapa.',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	122	, 'nb_barrio' => 'Andrés Sanin.',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	123	, 'nb_barrio' => 'Base Aérea.',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	124	, 'nb_barrio' => 'El Vivero',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	125	, 'nb_barrio' => 'Fepicol.',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	126	, 'nb_barrio' => 'La Playa.',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	127	, 'nb_barrio' => 'Las Ceibas.',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	128	, 'nb_barrio' => 'Las Veraneras.',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	129	, 'nb_barrio' => 'Los Pinos.',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	130	, 'nb_barrio' => 'Puerto Mallarino.',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	131	, 'nb_barrio' => 'Puerto Nuevo.',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	132	, 'nb_barrio' => 'San Marino.',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	133	, 'nb_barrio' => 'Siete de Agosto.',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 7, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	134	, 'nb_barrio' => 'Atanasio Girardot',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	135	, 'nb_barrio' => 'Benjamín Herrera',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	136	, 'nb_barrio' => 'Chapinero',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	137	, 'nb_barrio' => 'El trébol',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	138	, 'nb_barrio' => 'El troncal',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	139	, 'nb_barrio' => 'Industrial',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	140	, 'nb_barrio' => 'La Base',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	141	, 'nb_barrio' => 'La Floresta',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	142	, 'nb_barrio' => 'La Nueva Base',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	143	, 'nb_barrio' => 'Las Américas',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	144	, 'nb_barrio' => 'Municipal',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	145	, 'nb_barrio' => 'Primitivo Crespo',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	146	, 'nb_barrio' => 'Rafael Uribe Uribe',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	147	, 'nb_barrio' => 'Saavedra Galindo',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	148	, 'nb_barrio' => 'Santa Fe',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	149	, 'nb_barrio' => 'Santa Mónica Popular',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	150	, 'nb_barrio' => 'Simón Bolívar',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	151	, 'nb_barrio' => 'Urbanización La Base',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	152	, 'nb_barrio' => 'Villacolombia',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 8, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	153	, 'nb_barrio' => 'Alameda',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	154	, 'nb_barrio' => 'Aranjuez',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	155	, 'nb_barrio' => 'Belalcázar',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	156	, 'nb_barrio' => 'Bretaña',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	157	, 'nb_barrio' => 'Guayaquil',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	158	, 'nb_barrio' => 'Junín',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	159	, 'nb_barrio' => 'Manuel María Buenaventura',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	160	, 'nb_barrio' => 'Obrero',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	161	, 'nb_barrio' => 'Santa Mónica Belalcázar',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	162	, 'nb_barrio' => 'Sector La Luna',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	163	, 'nb_barrio' => 'Sucre',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 9, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	164	, 'nb_barrio' => 'Colseguros Andes',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	165	, 'nb_barrio' => 'Cristóbal Colon',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' =>	10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	166	, 'nb_barrio' => 'Departamental',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	167	, 'nb_barrio' => 'El Dorado',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	168	, 'nb_barrio' => 'Guabal',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	169	, 'nb_barrio' => 'Jorge Zawadsky',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	170	, 'nb_barrio' => 'La Libertad',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' =>	10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	171	, 'nb_barrio' => 'La Selva',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	172	, 'nb_barrio' => 'Las Acacias',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	173	, 'nb_barrio' => 'Las Granjas',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	174	, 'nb_barrio' => 'Olímpico',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	175	, 'nb_barrio' => 'Panamericano',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	176	, 'nb_barrio' => 'Pasamacho',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	177	, 'nb_barrio' => 'San Cristóbal',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	178	, 'nb_barrio' => 'San Judas Tadeo 1',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	179	, 'nb_barrio' => 'San Judas Tadeo 2',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	180	, 'nb_barrio' => 'Santa Elena',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	181	, 'nb_barrio' => 'Santo Domingo',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 10, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	182	, 'nb_barrio' => '20 de julio',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	183	, 'nb_barrio' => 'Agua blanca',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	184	, 'nb_barrio' => 'Ciudad Modelo',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	185	, 'nb_barrio' => 'El jardín',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	186	, 'nb_barrio' => 'El prado',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	187	, 'nb_barrio' => 'El recuerdo',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	188	, 'nb_barrio' => 'José Holguín Garcés',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	189	, 'nb_barrio' => 'JoseMaría Córdoba',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	190	, 'nb_barrio' => 'La Esperanza',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	191	, 'nb_barrio' => 'La Fortaleza',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	192	, 'nb_barrio' => 'La Independencia',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	193	, 'nb_barrio' => 'La Primavera',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	194	, 'nb_barrio' => 'León XIII',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	195	, 'nb_barrio' => 'Los Conquistadores',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	196	, 'nb_barrio' => 'Los Sauces',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	197	, 'nb_barrio' => 'Maracaibo',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	198	, 'nb_barrio' => 'Prados de Oriente',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	199	, 'nb_barrio' => 'San Benito',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	200	, 'nb_barrio' => 'San Carlos',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	201	, 'nb_barrio' => 'San Pedro Claver',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	202	, 'nb_barrio' => 'Urbanización Boyacá',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	203	, 'nb_barrio' => 'Villa del Sur',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	204	, 'nb_barrio' => 'villa nueva',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 11, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	205	, 'nb_barrio' => 'Alfonso Barberena',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	206	, 'nb_barrio' => 'Asturias',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	207	, 'nb_barrio' => 'Bello Horizonte',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	208	, 'nb_barrio' => 'Doce de Octubre',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	209	, 'nb_barrio' => 'Eduardo Santos',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	210	, 'nb_barrio' => 'El Paraíso',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	211	, 'nb_barrio' => 'FenalcoKennedy',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	212	, 'nb_barrio' => 'Julio Rincon',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	213	, 'nb_barrio' => 'Nueva Floresta',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	214	, 'nb_barrio' => 'Rodeo',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	215	, 'nb_barrio' => 'Sindical',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	216	, 'nb_barrio' => 'Villanueva',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 12, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	217	, 'nb_barrio' => 'Calipso',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	218	, 'nb_barrio' => 'Charco Azul',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	219	, 'nb_barrio' => 'El Diamante',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	220	, 'nb_barrio' => 'El Poblado I',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	221	, 'nb_barrio' => 'El Poblado II',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	222	, 'nb_barrio' => 'El Pondaje',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	223	, 'nb_barrio' => 'El Vergel',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	224	, 'nb_barrio' => 'La Paz',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	225	, 'nb_barrio' => 'Lleras Restrepo',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	226	, 'nb_barrio' => 'Lleras-Cinta larga',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	227	, 'nb_barrio' => 'Los Comuneros II',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	228	, 'nb_barrio' => 'Los Lagos I',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	229	, 'nb_barrio' => 'Los Lagos II',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	230	, 'nb_barrio' => 'Los Robles',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	231	, 'nb_barrio' => 'Marroquín III',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	232	, 'nb_barrio' => 'Nuevo Horizonte',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	233	, 'nb_barrio' => 'Omar Torrijos',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	234	, 'nb_barrio' => 'Ricardo Balcázar',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	235	, 'nb_barrio' => 'Rodrigo Lara Bonilla',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	236	, 'nb_barrio' => 'Sector Asprosocial–Diamante',  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	237	, 'nb_barrio' => 'Sector Laguna del Pondaje',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	238	, 'nb_barrio' => 'Ulpiano Lloreda',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	239	, 'nb_barrio' => 'Villa Blanca',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	240	, 'nb_barrio' => 'Villa del Lago',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	241	, 'nb_barrio' => 'Yira Castro',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 13, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	242	, 'nb_barrio' => 'Alfonso Bonilla Aragon',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	243	, 'nb_barrio' => 'Alirio Mora Beltrán',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	244	, 'nb_barrio' => 'José Manuel Marroquín 1',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	245	, 'nb_barrio' => 'José Manuel Marroquín 2',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	246	, 'nb_barrio' => 'Las Orquídeas',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	247	, 'nb_barrio' => 'Manuela Beltrán',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	248	, 'nb_barrio' => 'Naranjos 1',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	249	, 'nb_barrio' => 'Naranjos 2',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	250	, 'nb_barrio' => 'Promociones Populares',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	251	, 'nb_barrio' => 'Puertas del Sol',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 14, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	252	, 'nb_barrio' => 'Bajos de Ciudad Córdob',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	253	, 'nb_barrio' => 'Ciudad Córdoba',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	254	, 'nb_barrio' => 'Comuneros I',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	255	, 'nb_barrio' => 'Laureano Gómez',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	256	, 'nb_barrio' => 'Mojica',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	257	, 'nb_barrio' => 'Retiro',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	258	, 'nb_barrio' => 'Vallado',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 15, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	259	, 'nb_barrio' => 'Antonio Nariño',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	260	, 'nb_barrio' => 'Brisas del Limonar',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	261	, 'nb_barrio' => 'Ciudad 2000',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	262	, 'nb_barrio' => 'La Alborada',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	263	, 'nb_barrio' => 'Mariano Ramos',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	264	, 'nb_barrio' => 'Republica de Israel',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	265	, 'nb_barrio' => 'Unión de Vivienda Popular',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 16, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	266	, 'nb_barrio' => 'Bosques del Limonar',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	267	, 'nb_barrio' => 'Caney',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	268	, 'nb_barrio' => 'Cañaverales',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	269	, 'nb_barrio' => 'Ciudad Campestre',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	270	, 'nb_barrio' => 'Ciudad Capri',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	271	, 'nb_barrio' => 'Ciudad Universitaria',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	272	, 'nb_barrio' => 'Ciudadela Comfandi',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	273	, 'nb_barrio' => 'Ciudadela Paso ancho',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	274	, 'nb_barrio' => 'Club Campestre',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	275	, 'nb_barrio' => 'El Gran Limonar –Cataya',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	276	, 'nb_barrio' => 'El Ingenio',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	277	, 'nb_barrio' => 'El Limonar',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	278	, 'nb_barrio' => 'La Hacienda',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	279	, 'nb_barrio' => 'La Playa',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	280	, 'nb_barrio' => 'La Selva',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	281	, 'nb_barrio' => 'Las Quintas de don Simón',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	282	, 'nb_barrio' => 'Las Vegas',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	283	, 'nb_barrio' => 'Lili',                         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	284	, 'nb_barrio' => 'Los Portales',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	285	, 'nb_barrio' => 'Los Samanes',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	286	, 'nb_barrio' => 'Mayapan',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	287	, 'nb_barrio' => 'Nuevo Rey',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	288	, 'nb_barrio' => 'Parcelaciones Pance',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	289	, 'nb_barrio' => 'Prados del Limonar',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	290	, 'nb_barrio' => 'Primero de Mayo',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	291	, 'nb_barrio' => 'Santa Anita',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	292	, 'nb_barrio' => 'Unicentro',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	293	, 'nb_barrio' => 'Urbanización Ciudad Jardín',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	294	, 'nb_barrio' => 'Urbanización Rio Lili',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	295	, 'nb_barrio' => 'Urbanización San Joaquín',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 17, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	296	, 'nb_barrio' => 'Alférez Real',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	297	, 'nb_barrio' => 'Alto Nápoles',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	298	, 'nb_barrio' => 'Buenos Aires',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	299	, 'nb_barrio' => 'Caldas',                       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	300	, 'nb_barrio' => 'Colinas del Sur',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	301	, 'nb_barrio' => 'Cuarteles de Nápoles',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	302	, 'nb_barrio' => 'El Jordán',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	303	, 'nb_barrio' => 'Farallones',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	304	, 'nb_barrio' => 'Francisco Eladio Ramírez',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	305	, 'nb_barrio' => 'Horizontes',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	306	, 'nb_barrio' => 'Los Chorros',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	307	, 'nb_barrio' => 'Lourdes',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	308	, 'nb_barrio' => 'Mario Correa Rengifo',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	309	, 'nb_barrio' => 'Meléndez',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	310	, 'nb_barrio' => 'Nápoles',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	311	, 'nb_barrio' => 'Prados del Sur',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	312	, 'nb_barrio' => 'Sector Alto Jordán',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 18, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	313	, 'nb_barrio' => 'Bellavista',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	314	, 'nb_barrio' => 'Cambulos',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	315	, 'nb_barrio' => 'Camino Real Los Fundadores',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	316	, 'nb_barrio' => 'Cañaveralejo',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	317	, 'nb_barrio' => 'Champagnat',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	318	, 'nb_barrio' => 'Cristales',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	319	, 'nb_barrio' => 'Cuarto de Legua',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	320	, 'nb_barrio' => 'El Cedro',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	321	, 'nb_barrio' => 'El Lido',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	322	, 'nb_barrio' => 'El Mortiñal',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	323	, 'nb_barrio' => 'Eucarístico',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	324	, 'nb_barrio' => 'Galindo',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	325	, 'nb_barrio' => 'Guadalupe',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	326	, 'nb_barrio' => 'La Cascada',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	327	, 'nb_barrio' => 'Miraflores',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	328	, 'nb_barrio' => 'Nuevo Tequendama',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	329	, 'nb_barrio' => 'Pampa Linda',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	330	, 'nb_barrio' => 'Plaza de Toros',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	331	, 'nb_barrio' => 'Refugio',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	332	, 'nb_barrio' => 'San Fernando Nuevo',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	333	, 'nb_barrio' => 'San Fernando Viejo',           'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	334	, 'nb_barrio' => 'Santa Bárbara',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	335	, 'nb_barrio' => 'Santa Isabel',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	336	, 'nb_barrio' => 'Sector Altos de Santa Isabel', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	337	, 'nb_barrio' => 'Sector Bosque Municipal',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	338	, 'nb_barrio' => 'Sector CañaveralejoGuadalupe', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	339	, 'nb_barrio' => 'Sector la Patria Cañaveral',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	340	, 'nb_barrio' => 'Tejares',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	341	, 'nb_barrio' => 'Tres de Julio',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	342	, 'nb_barrio' => 'Unidad Dep. Alberto Galindo',  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	343	, 'nb_barrio' => 'Unidad Panamericana',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	344	, 'nb_barrio' => 'Unidad Residencial El Coliseo','tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	345	, 'nb_barrio' => 'Unidad Res. Santiago de Cali', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	346	, 'nb_barrio' => 'Urbanización Colseguros',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	347	, 'nb_barrio' => 'Urbanización Militar',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	348	, 'nb_barrio' => 'Urbanización Nueva Granada',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	349	, 'nb_barrio' => 'Urbanización Tequendama',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 19, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	350	, 'nb_barrio' => 'Belén',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	351	, 'nb_barrio' => 'Belisario Caicedo',            'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	352	, 'nb_barrio' => 'Brisas de Mayo',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	353	, 'nb_barrio' => 'Cementerio Carabineros',       'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	354	, 'nb_barrio' => 'Cortijo',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	355	, 'nb_barrio' => 'La Sultana',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	356	, 'nb_barrio' => 'Lleras Camargo',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	357	, 'nb_barrio' => 'Pueblo Joven',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	358	, 'nb_barrio' => 'Siloe',                        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	359	, 'nb_barrio' => 'Tierra Blanca',                'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	360	, 'nb_barrio' => 'Urbanización Cañaveralejo',    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	361	, 'nb_barrio' => 'Urbanización Cortij',          'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	362	, 'nb_barrio' => 'Urbanización Venezuela.',      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	363	, 'nb_barrio' => 'Venezuela',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 20, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	364	, 'nb_barrio' => 'Calimio Desepaz',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	365	, 'nb_barrio' => 'Ciudad Talanga',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	366	, 'nb_barrio' => 'Ciudadela del Rio-CVC',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	367	, 'nb_barrio' => 'Compartir',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	368	, 'nb_barrio' => 'DesepazInvicali',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	369	, 'nb_barrio' => 'Las Dalias',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	370	, 'nb_barrio' => 'Las Garzas',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	371	, 'nb_barrio' => 'Los Lideres',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	372	, 'nb_barrio' => 'Pizamos 1',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	373	, 'nb_barrio' => 'Pizamos 2',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	374	, 'nb_barrio' => 'PizamosIII',                   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	375	, 'nb_barrio' => 'Plantan Tto Puerto Mallarino', 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	376	, 'nb_barrio' => 'Potrero Grande',               'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	377	, 'nb_barrio' => 'Remanso',                      'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	378	, 'nb_barrio' => 'Santa Clara',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	379	, 'nb_barrio' => 'Valle Grande',                 'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	380	, 'nb_barrio' => 'Villa Luz',                    'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	381	, 'nb_barrio' => 'Villa mercedes I',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 21, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	382	, 'nb_barrio' => 'Ciudad Campestre',             'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	383	, 'nb_barrio' => 'Condominio Miramontes',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	384	, 'nb_barrio' => 'Haciendas de Alferez',         'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	385	, 'nb_barrio' => 'Jardín de Pance',              'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	386	, 'nb_barrio' => 'Jockey Club',                  'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	387	, 'nb_barrio' => 'Reamansode Ciudad jardin',     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	388	, 'nb_barrio' => 'Urbanización ciudad Jardín',   'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	389	, 'nb_barrio' => 'Urbanización Rio Lili',        'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],
            ['co_barrio' =>	390	, 'nb_barrio' => 'Verdanza',                     'tx_latitud' => '', 'tx_longitud' => '', 'id_comuna' => 22, 'id_status' => 1, 'id_usuario' => 1],

        ]);

            //// php artisan db:seed --class=BarrioSeeder
        
    }
}
